spring:
  liquibase:
    enabled: true
    contexts: local
    change-log: classpath:/db/changelog/db.changelog-master.xml
  application:
    name: pureplate
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:classpath:/data/localdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    database: H2
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# Spring Actuator
management:
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
